### ISSUE TITLE
Not really an issue, but...

### ISSUE THREAD

**Issue by 3871968** [nucular/gofigure#1]
This should have the main goal of supporting logs in the energymech format as that is what jacksonmj feeds the existing PISG.

I'll start writing the parser if you want. 

Now, the important question: camel case or underscores in variable names?

**Comment by nucular** [comment]
Resolved with 607cde53986429c42b8701f2e36042656e9e6309.
And I propose camelCase for methods, PascalCase for classes,  lowercase for primitive variables, UPPERCASE for constants.

**Comment by nucular** [comment]
Resolved with 607cde53986429c42b8701f2e36042656e9e6309.
And I propose camelCase for methods, PascalCase for classes,  lowercase for primitive variables, UPPERCASE for constants.
