### ISSUE TITLE
Another non-issue...

### ISSUE THREAD

**Issue by 3871968** [nucular/gofigure#2]
I have scraped logs from January 6, 2013 (the earliest it will go) to November 12, 2015 from mniip's website to use for testing. They are in an unknown format, but I could write a parser for it. Should I?

**Comment by nucular** [comment]
Might be useful for testing, so go for it. You can just use most of the code from the EnergyMech parser I guess. Maybe even make it fetch the logs from the server directly or something.

**Comment by 3871968** [comment]
I already have Python code to fetch the logs from the server (that is how I did it), but since it is about 150 MB of logs that took 2 hours to download, I don't think that downloading them directly will work very well.

Also: all bans since January 2013 in a separate file if you want to see it. I am working on generating some statistics about the bans now. So far the amount of users banned for different reasons seems to line up pretty well with what people said in my survey about rule violations.

**Comment by 3871968** [comment]
Done.
